baseURL = "https://sungjunyoung.github.io/"
languageCode = "en-us"
title = "sungjunyoung"
theme = "hello-friend"
paginate = 5
googleAnalytics = "G-CMFR9WZ898"
enableInlineShortcodes = true
enableEmoji = "true"

[params]
  defaultTheme = "dark"
  showMenuItems = 2
  toc = true
  rssFullText = false

[languages]
  [languages.en]
    title = "sungjunyoung"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read More"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "sungjunyoung"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"